name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          ./build.sh

      - name: Run Tests
        run: |
          ./build.sh  # You can call the same build script to run tests

